
# Enabling Antigen https://github.com/zsh-users/antigen
source ~/.antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle colored-man-pages
antigen bundle colorize
antigen bundle cp
antigen bundle history-substring-search
antigen bundle iterm2
antigen bundle jira
#antigen bundle nomad
antigen bundle screen
antigen bundle ssh-agent
antigen bundle systemadmin
antigen bundle torrent
#antigen bundle vagrant
antigen bundle zsh-navigation-tools
antigen bundle autojump
#antigen bundle zsh-autosuggestions

# Python Plugins
#antigen bundle pip
#antigen bundle python
#antigen bundle virtualenv


# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Load the theme.
# antigen theme robbyrussell

# Tell Antigen that you're done.
antigen apply

# Sourcing Theme configs
source ~/git/CustomConfigs/zsh/custom_agnoster-theme.zsh

# Sourcing Aliases
source ~/git/CustomConfigs/zsh/aliases.zsh

# Sourcing zstyle configs
source ~/git/CustomConfigs/zsh/zstyles.zsh

# Sourcing setopt configs
source ~/git/CustomConfigs/zsh/setopt.zsh

# Sourcing ZSH mod configs
source ~/git/CustomConfigs/zsh/modules.zsh

# Sourcing Key binding configs
source ~/git/CustomConfigs/zsh/key_bindings.zsh

# Sourcing some extra zsh configs
source ~/git/CustomConfigs/zsh/extra.zsh

# Sourcing installed plugins configs
source ~/git/CustomConfigs/zsh/plugins_configs.zsh

# Sourcing my custom ZSH variables
source ~/git/CustomConfigs/zsh/variables.zsh
